// Liste complète des secteurs d'entreprise pour Apollo
export const INDUSTRY_SECTORS = [
  { value: "", label: "Tous les secteurs" },
  { value: "Accounting", label: "Comptabilité" },
  { value: "Airlines/Aviation", label: "Aéronautique/Aviation" },
  { value: "Alternative Medicine", label: "Médecine alternative" },
  { value: "Apparel & Fashion", label: "Mode & Vêtements" },
  { value: "Architecture & Planning", label: "Architecture & Urbanisme" },
  { value: "Automotive", label: "Automobile" },
  { value: "Aviation & Aerospace", label: "Aviation & Aérospatiale" },
  { value: "Banking", label: "Banque" },
  { value: "Biotechnology", label: "Biotechnologie" },
  { value: "Broadcast Media", label: "Médias audiovisuels" },
  { value: "Building Materials", label: "Matériaux de construction" },
  { value: "Business Supplies and Equipment", label: "Fournitures professionnelles" },
  { value: "Capital Markets", label: "Marchés financiers" },
  { value: "Chemicals", label: "Chimie" },
  { value: "Civil Engineering", label: "Génie civil" },
  { value: "Commercial Real Estate", label: "Immobilier commercial" },
  { value: "Computer & Network Security", label: "Sécurité informatique" },
  { value: "Computer Games", label: "Jeux vidéo" },
  { value: "Computer Hardware", label: "Matériel informatique" },
  { value: "Computer Networking", label: "Réseaux informatiques" },
  { value: "Computer Software", label: "Logiciels" },
  { value: "Construction", label: "Construction" },
  { value: "Consumer Electronics", label: "Électronique grand public" },
  { value: "Consumer Goods", label: "Biens de consommation" },
  { value: "Consumer Services", label: "Services aux consommateurs" },
  { value: "Cosmetics", label: "Cosmétiques" },
  { value: "Defense & Space", label: "Défense & Spatial" },
  { value: "Design", label: "Design" },
  { value: "E-Learning", label: "E-Learning" },
  { value: "Education Management", label: "Gestion de l'éducation" },
  { value: "Electrical/Electronic Manufacturing", label: "Fabrication électronique" },
  { value: "Entertainment", label: "Divertissement" },
  { value: "Environmental Services", label: "Services environnementaux" },
  { value: "Events Services", label: "Services événementiels" },
  { value: "Facilities Services", label: "Services aux installations" },
  { value: "Farming", label: "Agriculture" },
  { value: "Financial Services", label: "Services financiers" },
  { value: "Food & Beverages", label: "Alimentation & Boissons" },
  { value: "Food Production", label: "Production alimentaire" },
  { value: "Furniture", label: "Mobilier" },
  { value: "Government Administration", label: "Administration publique" },
  { value: "Graphic Design", label: "Design graphique" },
  { value: "Health, Wellness and Fitness", label: "Santé & Bien-être" },
  { value: "Higher Education", label: "Enseignement supérieur" },
  { value: "Hospital & Health Care", label: "Hôpitaux & Soins de santé" },
  { value: "Hospitality", label: "Hôtellerie" },
  { value: "Human Resources", label: "Ressources humaines" },
  { value: "Import and Export", label: "Import et Export" },
  { value: "Industrial Automation", label: "Automatisation industrielle" },
  { value: "Information Services", label: "Services d'information" },
  { value: "Information Technology and Services", label: "Technologies de l'information" },
  { value: "Insurance", label: "Assurance" },
  { value: "International Trade and Development", label: "Commerce international" },
  { value: "Internet", label: "Internet" },
  { value: "Investment Banking", label: "Banque d'investissement" },
  { value: "Investment Management", label: "Gestion d'investissements" },
  { value: "Law Practice", label: "Cabinet d'avocats" },
  { value: "Legal Services", label: "Services juridiques" },
  { value: "Leisure, Travel & Tourism", label: "Loisirs & Tourisme" },
  { value: "Logistics and Supply Chain", label: "Logistique et Supply Chain" },
  { value: "Luxury Goods & Jewelry", label: "Produits de luxe" },
  { value: "Machinery", label: "Machinerie" },
  { value: "Management Consulting", label: "Conseil en management" },
  { value: "Maritime", label: "Maritime" },
  { value: "Market Research", label: "Études de marché" },
  { value: "Marketing and Advertising", label: "Marketing et Publicité" },
  { value: "Mechanical or Industrial Engineering", label: "Génie mécanique/industriel" },
  { value: "Media Production", label: "Production médiatique" },
  { value: "Medical Devices", label: "Dispositifs médicaux" },
  { value: "Medical Practice", label: "Cabinet médical" },
  { value: "Mental Health Care", label: "Soins de santé mentale" },
  { value: "Mining & Metals", label: "Mines & Métaux" },
  { value: "Motion Pictures and Film", label: "Cinéma" },
  { value: "Music", label: "Musique" },
  { value: "Nanotechnology", label: "Nanotechnologie" },
  { value: "Non-Profit Organization Management", label: "Organisations à but non lucratif" },
  { value: "Oil & Energy", label: "Pétrole & Énergie" },
  { value: "Online Media", label: "Médias en ligne" },
  { value: "Outsourcing/Offshoring", label: "Externalisation" },
  { value: "Package/Freight Delivery", label: "Livraison de colis/fret" },
  { value: "Packaging and Containers", label: "Emballage" },
  { value: "Performing Arts", label: "Arts du spectacle" },
  { value: "Pharmaceuticals", label: "Pharmaceutique" },
  { value: "Photography", label: "Photographie" },
  { value: "Plastics", label: "Plastiques" },
  { value: "Primary/Secondary Education", label: "Enseignement primaire/secondaire" },
  { value: "Printing", label: "Imprimerie" },
  { value: "Professional Training & Coaching", label: "Formation professionnelle" },
  { value: "Public Relations and Communications", label: "Relations publiques" },
  { value: "Publishing", label: "Édition" },
  { value: "Real Estate", label: "Immobilier" },
  { value: "Renewables & Environment", label: "Énergies renouvelables" },
  { value: "Research", label: "Recherche" },
  { value: "Restaurants", label: "Restaurants" },
  { value: "Retail", label: "Commerce de détail" },
  { value: "Security and Investigations", label: "Sécurité" },
  { value: "Semiconductors", label: "Semi-conducteurs" },
  { value: "Sporting Goods", label: "Articles de sport" },
  { value: "Sports", label: "Sports" },
  { value: "Staffing and Recruiting", label: "Recrutement" },
  { value: "Supermarkets", label: "Supermarchés" },
  { value: "Telecommunications", label: "Télécommunications" },
  { value: "Textiles", label: "Textiles" },
  { value: "Transportation/Trucking/Railroad", label: "Transport/Camionnage" },
  { value: "Utilities", label: "Services publics" },
  { value: "Venture Capital & Private Equity", label: "Capital-risque" },
  { value: "Warehousing", label: "Entreposage" },
  { value: "Wholesale", label: "Commerce de gros" },
  { value: "Wine and Spirits", label: "Vins et Spiritueux" },
  { value: "Wireless", label: "Sans fil" },
  { value: "Writing and Editing", label: "Rédaction et Édition" },
]
