import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image, Font } from '@react-pdf/renderer';

// Register fonts (using standard fonts for now to avoid loading issues)
// In production, you would register Inter or custom fonts

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
    padding: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#C69C6D', // Vyxo Gold
    paddingBottom: 10,
  },
  logoText: {
    fontSize: 24,
    color: '#0F2339', // Vyxo Navy
    fontWeight: 'bold',
  },
  logoAccent: {
    color: '#C69C6D',
  },
  title: {
    fontSize: 18,
    marginBottom: 10,
    color: '#0F2339',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  section: {
    margin: 10,
    padding: 10,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 5,
  },
  label: {
    width: 120,
    fontSize: 10,
    color: '#666',
    fontWeight: 'bold',
  },
  value: {
    fontSize: 10,
    color: '#000',
  },
  scoreBox: {
    position: 'absolute',
    top: 40,
    right: 40,
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#0F2339',
    justifyContent: 'center',
    alignItems: 'center',
  },
  scoreText: {
    color: '#C69C6D',
    fontSize: 24,
    fontWeight: 'bold',
  },
  scoreLabel: {
    color: '#FFF',
    fontSize: 8,
  },
  table: {
    display: "flex",
    width: "auto",
    borderStyle: "solid",
    borderWidth: 1,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    marginTop: 20,
  },
  tableRow: {
    margin: "auto",
    flexDirection: "row",
  },
  tableCol: {
    width: "25%",
    borderStyle: "solid",
    borderWidth: 1,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCell: {
    margin: "auto",
    marginTop: 5,
    fontSize: 10,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    color: '#999',
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: '#EEE',
    paddingTop: 10,
  }
});

interface AuditData {
  clientName: string;
  auditDate: string;
  auditorName: string;
  score: number;
  findings: { id: string; question: string; answer: string }[];
}

export const AuditPDF = ({ data }: { data: AuditData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <Text style={styles.logoText}>VYXO<Text style={styles.logoAccent}>.CH</Text></Text>
        <Text style={{ fontSize: 10, color: '#666', marginTop: 10 }}>Ref: AUD-{new Date().getFullYear()}-001</Text>
      </View>

      {/* Title & Score */}
      <View style={{ marginTop: 20 }}>
        <Text style={styles.title}>Audit Report</Text>
        <View style={styles.row}>
          <Text style={styles.label}>Client:</Text>
          <Text style={styles.value}>{data.clientName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Date:</Text>
          <Text style={styles.value}>{data.auditDate}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>Auditor:</Text>
          <Text style={styles.value}>{data.auditorName}</Text>
        </View>
      </View>

      <View style={styles.scoreBox}>
        <Text style={styles.scoreText}>{data.score}</Text>
        <Text style={styles.scoreLabel}>SCORE</Text>
      </View>

      {/* Findings Table */}
      <View style={{ marginTop: 40 }}>
        <Text style={{ fontSize: 14, marginBottom: 10, color: '#0F2339', fontWeight: 'bold' }}>Detailed Findings</Text>
        {data.findings.map((finding, i) => (
            <View key={i} style={{ marginBottom: 10, padding: 10, backgroundColor: i % 2 === 0 ? '#F9FAFB' : '#FFF' }}>
                <Text style={{ fontSize: 10, color: '#666', marginBottom: 4 }}>Question {i + 1}</Text>
                <Text style={{ fontSize: 11, color: '#000', marginBottom: 4 }}>{finding.question}</Text>
                <Text style={{ fontSize: 10, color: '#0F2339', fontWeight: 'bold' }}>Answer: {finding.answer}</Text>
            </View>
        ))}
      </View>

      {/* Footer */}
      <View style={styles.footer}>
        <Text>Generated by Vyxo Consult CentralHub • Confidential Document</Text>
        <Text>www.vyxo.com</Text>
      </View>
    </Page>
  </Document>
);
